#!/bin/sh

#port 22 is the hot relay
#port 27 is the ignite relay 
arg="$1"

if [ "$arg" = "ignite" ] ; then
    echo 1 > /sys/class/gpio/gpio27/value
    echo "relay on ignite"
elif [ "$arg" = "hot" ] ; then
    echo 1 > /sys/class/gpio/gpio22/value
    echo "relay on hot"
else
    echo “Wrong argument value.Use values hot or cold.”

fi